# This workflow is triggered when someone create a new release in GitHub
# and checks the "This is a pre-relase" box.
name: Trigger Release creation

on:
  release:
    types: [prereleased]

jobs:
  release-module:
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-release-module.yml@v2
    secrets: inherit
    with:
      primary_release_branch: "master"
      job_container: "ghcr.io/jahia/jahia-docker-mvn-cache:8-jdk-noble-mvn-loaded"
